thumbnails:
  - width: 550
    prefix: scaled_
    include:
    - '*.png'
    - '*.jpg'
  - width: 240
    height: 240
    prefix: thumb_
    crop_type: center
    include:
    - '*.png'
    - '*.jpg'
    
