thumbnails:
  - width: 550
    prefix: scaled_
    include:
    - '*.png'
    - '*.jpg'
  - width: 550
    height: 200
    prefix: listing_
    crop_type: center
    include: '*.jpg'
  - width: 240
    height: 240
    prefix: thumb_
    crop_type: center
    include:
    - '*.png'
    - '*.jpg'
  - width: 240
    height: 120
    prefix: thumb_narrow_
    crop_type: center
    include:
        - '*.png'
        - '*.jpg'
    
