mode: development
logger:
    level: warning 
media_root: media
media_url: /media
base_url: /
# If your site is nested inside of a bigger one, you can use media_url and
# base_url to properly generate links on your site. For example, if your URL
# will be some.domain.com/starter/, use:
#   media_url: /starter/media
#   base_url: /starter/
template: hyde.ext.templates.jinja.Jinja2Template
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.git.GitDatesPlugin
    - hyde.ext.plugins.gitTracker.GitTrackerPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.urls.UrlCleanerPlugin
    - hyde.ext.plugins.less.LessCSSPlugin
    - hyde.ext.plugins.images.ImageThumbnailsPlugin
#    - hyde.ext.plugins.images.ImageSizerPlugin
    - hyde.ext.plugins.sorter.SorterPlugin
    - hyde.ext.plugins.grouper.GrouperPlugin
    - hyde.ext.plugins.tagger.TaggerPlugin
    - hyde.ext.plugins.unflattener.UnflattenerPlugin
context:
    data:
        author:
            name: Sam Jacoby
            url: "http://samjacoby.com"
            email: sjacoby@media.mit.edu
        this_site:
            title: Sam Jacoby 
            url: "http://samjacoby.com"
        layout:
            name: Sam Jacoby 
            url: "http://samjacoby.com"
        project:
            name: Hyde
            url: "http://hyde.github.com"
            install: "http://hyde.github.com/install.html"
        menu:
          - title: Posts 
            key: posts 
            url: /posts/
          - title: Projects 
            key: projects
            url: /projects/
          - title: Printing
            key: printing
            url: /printing/ 

### Advanced part ###

# This defines meta data on the whole site.
meta:
    # 'nodemeta' will tell Hyde what file to look for inside a folder from
    # which to apply meta data to all files (resources) inside it. This is
    # a great way of simply adding or modifying properties of a very large
    # number of files.
    nodemeta: meta.yaml
    title: "Printer, Programmer, Explorer"
    language: en
    ga_tracking_code: UA-34337252-1
    keywords: "mit, high-low tech, shackman press, lettepress, printing, coding, programming, sam jacoby"

urlcleaner:
    index_file_names:
        # Identifies the files that represents a directory listing.
        # These file names are automatically stripped away when
        # the content_url function is called.
        - index.html
    strip_extensions:
        # The following extensions are automatically removed when
        # generating the urls using content_url function.
        - html
    # This option will append a slash to the end of directory paths
    append_slash: true

sorter:
    name: # the name of the sorter (no pun intended)
        attr: name # by which attributes will resources be sorted
        filters:
            source_file.kind: html
            # You can include only files from a certain folder.
            #resource.node: (name of the folder)
        reverse: True # if you need the list backwards
    multi:
        attr: meta.weight
        reverse: True
    date:
        attr: meta.date
        filters: 
            source_file.kind: html
        reverse: True
    order:
        attr: order
        filters:
            source_file.kind html
    file_type:
        attr: 
            - source_file.kind
            - source_file.size
    index:
        attr: meta.index
        filters:
            source_file.kind: html
    learning_order:
        attr: meta.learning_order
        filters:
            source_file.kind: html

grouper:
    category:
        sorter: name
        description: Various categories that items belong to.  
        groups:
            - name: posts
              sorter: date
              description:  This is where blog posts are
            - name: projects
              sorter: date
              description: These are projects
            - name: printing
              sorter: multi
              description: This is printing 

    # You can have more than one group section, depending on your needs.
    # For example: "categories", "menu sections", etc.
    #category:
    #    description: To which category a blog post belongs to.
    #    groups:
    #        - name: software
    #          description: Software engineering
    #        - name: web
    #          description: Web technologies
    #        - name: seo
    #          description: Search Engine Optimization

tagger:
    sorter: date
    reverse: True
publisher:
    sftp:
        type: hyde.ext.publishers.pyfs.PyFS
        url: shackman@shackmanpress.com:public_html/samjacoby.com
unflattener:
    folders:
        - posts 
gittracker:
    extensions:
        - html
